Javascript manipulation on hamburger
brightbrain20/Portfolio pull request #8
Opened 2023-01-03 21:48 UTC by azeezumoru

- My partner and I set up eslintrc.json file

- We created index.js file and linked it to the index.html

- Added event listener to the hamburger icon

2023-01-03 21:55 UTC, prolajumokeoni commented
Hi @azeezumoru and @brightbrain20, You are missing some sections in your readme, please add all sections from the microverse [readme template](https://github.com/microverseinc/readme-template)  to your readme for your own application

2023-01-03 22:03 UTC, prolajumokeoni commented
Hi @Team 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a descriptive readme,  You are missing some sections in your readme

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-03 22:17 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [x] Nice job using the Microverse readme template but there are a lot of section missing, So please add these sections (Getting started, Future Features, Show your support, and License) 

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-03 22:17 UTC, Omar-Muhamad commented on styles.css
> +  height: 100%;
- [ ] please add the correct padding or margin top value by decreasing it to match the given Figma design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/210449022-9ac8f98d-0bbe-4e69-9815-806646503d4a.png)  | ![image](https://user-images.githubusercontent.com/68796232/210449060-2af8b21f-d521-4842-9d63-1667a3467627.png) |

2023-01-03 22:17 UTC, Omar-Muhamad commented on index.html
> +        <li> <a href="#about-me" class="mobile-item">About</a></li>
- [ ] Clicking on the About mobile menu option suppose to show the `about me` section, not showing the page from the beginning.

![chrome-capture-2023-0-4](https://user-images.githubusercontent.com/68796232/210449708-239f5101-f367-4fd4-b771-fd4ad1f1be3f.gif)

2023-01-04 00:37 UTC, alexander16108 approved these changes
Hi @azeezumoru , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/mgdTACdScuYHgSp6nD/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 00:47 UTC, merged

2023-01-04 02:35 UTC, Reem-lab reviewed
Hi @Omar-Muhamad, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that you should submit your PR from your repo since this milestone you should both work in both projects but just submit the PR indvidually but now you submit your partner PR so kindly implement this also in your repo then submit your PR

![image](https://user-images.githubusercontent.com/58553711/210474050-a6510b03-6684-487c-9455-3316f111858e.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._